import api from "./api";


export const createOrderDetails = (orderDetails) => api.post('/orderdetails/save-colis', orderDetails);
export const getOrderDetails = (orderId, page) => api.get(`/orderdetails/ship/${orderId}?page=${page}&size=9&sort=id,DESC`);
export const getsOrderDetails = (orderId) => api.get(`/orderdetails/ships/${orderId}`);
export const searchOrderDetails = (orderId, orderDetailsId, page) => api.get(`/orderdetails/client/search/${orderId}?param=${orderDetailsId}&page=${page}&size=9&sort=id,DESC`);
export const searchsOrderDetails = (orderId, orderDetailsId) => api.get(`/orderdetails/client/searchs/${orderId}?param=${orderDetailsId}`);
export const listOrderDetails = (page) => api.get(`/orderdetails?page=${page}&size=7&sort=id,DESC`);
export const listOrderDetailsDashboard = () => api.get(`/orderdetails?page=0&size=1000&sort=id,DESC`);
export const listOrderDetailsEtendu = (page) => api.get(`/orderdetails/etendu?page=${page}&size=9&sort=id,DESC`);
export const searchlistOrderDetailsEtendu = (param,page) => api.get(`/orderdetails/searchetendu/${param}?page=${page}&size=9&sort=id,DESC`);
export const myOrderDetailsList = (usercode, page) => api.get(`/orderdetails/client/${usercode}?page=${page}&size=9&sort=id,DESC`);
export const myOrderDetailsDashboard = (usercode) => api.get(`/orderdetails/client/${usercode}?page=0&size=1000&sort=id,DESC`);
export const searchmyOrderDetails = (usercode, orderDetailsId, page) => api.get(`/orderdetails/findclient/${usercode}?search=${orderDetailsId}&page=${page}&size=9&sort=id,DESC`);
export const trackmyOrderDetails = (orderDetailsId) => api.get(`/orderdetails/trackcolis?search=${orderDetailsId}`);
export const downloadFacture = (usercode, orderDetailsId) => api.get(`/orderdetails/clentfacturedownload/${usercode}?search=${orderDetailsId}`, { responseType: 'blob' });
export const getOrderdetailsCity = (shiporder, page) => api.get(`/orderdetails/city/${shiporder}?page=${page}&size=50&sort=id,DESC`);
export const updateOrderDetailsStatus = (orderDetailsId) => api.put(`/orderdetails/updatedetails/${orderDetailsId}`);
export const downloadManifeste = (shiporder, cityID) => api.get(`/orderdetails/manifestdownload/${shiporder}?search=${cityID}`, { responseType: 'blob' });
export const surcursalOrderDetails = (branchcode, city) => api.get(`/orderdetails/city/${branchcode}/${city}`);
export const updateReceiveOrderDetails = (upc, city) => api.put(`/orderdetails/${upc}?cityID=${city}`);
export const getLivraisionDetailsCity = (shiporder, city) => api.get(`/orderdetails/livraison/${shiporder}?cityID=${city}`);
export const searchClientLivraison = (shiporder, city, client) => api.get(`/orderdetails/livraisonsearch/${shiporder}?cityID=${city}&search=${client}`);
export const updateColisStatus = (orderDetailsId,orderID) => api.put(`/orderdetails/updatecolis/${orderDetailsId}?id=${orderID}`);
export const deleteOrderDetails = (orderDetailsId) => api.delete("/orderdetails/" + orderDetailsId);
export const printColisLabel = (upc) =>api.get("/orderdetails/labeldownload/" + upc, {responseType: "blob", headers: {Accept: "application/pdf",},});
export const getTotalFactures = () => api.get("/orderdetails/objectif");
export const getTotalFacturesFromMyCity = (cityID) => api.get(`/orderdetails/objectifs/${cityID}`);
export const createSendOrderDetails = (orderDetails) => api.post('/orderdetails', orderDetails);
export const colisvilleGraphe = (shiporder) => api.get(`/orderdetails/graphecolisparville/${shiporder}`);
export const amountvilleGraphe = (shiporder) => api.get(`/orderdetails/grapheamountparville/${shiporder}`);
export const updateOrderDetails = (orderDetailsId, orderDetails) => api.put(`/orderdetails/actualiser/${orderDetailsId}`, orderDetails);
export const transferOrderDetails = (orderDetailsId, orderId) => api.put(`/orderdetails/transfer/${orderDetailsId}?order_id=${orderId}`);
export const findClientInOrderDetails = (orderID) => api.get(`/orderdetails/findclientinorder/${orderID}`);
export const searchClientInOrderDetails = (orderID, search) => api.get(`/orderdetails/searchclientinorder/${orderID}?search=${search}`);
export const getClientInOrderDetails = (orderID, search) => api.get(`/orderdetails/getclientinorder/${orderID}?search=${search}`);
export const getAllOrderDetails = (page) => api.get(`/orderdetails?page=${page}&size=25&sort=id,DESC`);
export const searchAllOrderDetails = (search, page) => api.get(`/orderdetails/alldetails/${search}?page=${page}&size=25&sort=id,DESC`);
export const downloadColisClient = (param) => api.get(`/orderdetails/clientdownload/${param}`, { responseType: 'blob' });
